name: Main
on:
  push:
    branches:
      - "quickfix"
  pull_request:
    branches:
      - "quickfix"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "running tests"
        if: github.head_ref == 'quickfix'
          echo "done"
        else
          echo "not done"

# jobs:
#   Check tags:
#    steps:
#   - uses: actions/checkout@v2
#   - run: |
#       ls
#       echo ${{ github.ref }}
#       ref='refs/tags/v'
#       if [[ ${{ github.ref }} == *${ref}* ]]; then
#         v=$(echo ${{ github.ref }} | cut -d'/' -f3)
#         echo "version tag is ${v}"
#       else
#         echo "There is no github tag reference, skipping"
#       fi