name: pr_comment


on:
  pull_request:
    types: [opened, synchronize]

jobs:
  history:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
