name: Notifier

on:
  push:

jobs:
     Comment_issue:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: README.md
          labels: |
            report
            automated issue

