name: Jenkins 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
jobs:

  build_jenkins_container:
    runs-on: self-hosted
    steps:
      - name: Get data
        run: git pull
      - name: Start containers
        run: docker-compose up --build --remove-orphans -d
        #run: chmod +x runner.sh && ./runner.sh         

