name: Jenkins 
on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
jobs:

  build_jenkins_container:
    runs-on: self-hosted
    steps:
      - name: Get data
        run: git pull
      - name: Start containers
        run: docker-compose up --build -d 
      - name: Remove containers
        run: docker system prune -a
        
  Jenkins:
    runs-on: self-hosted
    needs: build_jenkins_container
    steps:
      - name: Run Jenkins
        run: curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} http://jenkinstestnow.ddns.net/job/testerosa/build
  
  Create_comment_for_PR:
    name: PR_comment
    runs-on: ubuntu-latest
    needs: Jenkins
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p output/
      - run: curl -s ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}@jenkinstestnow.ddns.net/job/testerosa/lastBuild/consoleText |sed -n '9'p > output/output.txt 
      - uses: actions/upload-artifact@v1
        with:
          name: output  
          path: output
      - uses: actions/download-artifact@v1
        with:
          name: output
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: output/output.txt    
