name: Clean Workflow Logs

on:
  workflow_call:
    inputs:
      days_old:
       type: number
       description: "The amount of days old to delete"
       default: ""
       required: false
  workflow_dispatch:

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: ${{ github.event.inputs.days_old }}
